# Copyright 2025 The Torch-Spyre Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The cost report a reviewer confirms, rendered so a diff names what moved.

Asking an author to write down what a kernel should cost is the highest-value
check available and the one most likely to be waived away, because deriving it is
work.  Asking a reviewer to *confirm* a derivation is nearly free.  So the tool
derives it and commits the result: the figures arrive in the pull request as a
readable attribution, and a claim in prose that disagrees with the table beside
it does not survive review.

That inversion is why this file exists at all.  It is also the whole of what this
mechanism can do: the derivation is computed by the same code that produces the
measurement, so a mis-charged operation moves the total and its breakdown together
and the page stays self-consistent.  Whether the model itself charges correctly is
a question about the model rather than about any one kernel, and is asked in
``tests/test_latency.py``, against hand-counted bytes, FLOPs and cycles.

All of them land in one generated document, ``docs/kernel_cost.md``, a section per
kernel.  One file rather than one beside each ``.mlir`` because a derivation is not
a fact about a kernel a reader goes looking for individually — it is the cost of the
repository, read down the page and diffed as a whole, and eighteen files repeated
this module's caveat eighteen times.

Two rendering rules, both there so the committed file is a useful diff:

* Every figure is formatted to four significant digits.  A verbatim comparison on
  full-precision floats would fail on last-bit noise and teach people to ignore
  it.
* Nothing varies between runs at fixed parameters — no timestamps, no dictionary
  iteration order, no host detail.  A diff must mean the cost changed.
"""

from __future__ import annotations

import math
import re
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

#: The generated document every derivation is a section of.
DOCUMENT = "docs/kernel_cost.md"

TITLE = "# Kernel cost derivations"
HEADER = ("<!-- Generated by `python -m ktir_cpu.kernelentry adopt --all`. "
          "Do not edit by hand. -->")
PREAMBLE = """\
One section per declared kernel, at the parameters its declaration gates on.  Each
is what the cost model reports, **not an independent check of it**: the figures and
the totals they sum to come from the same code, so a mis-charged op moves both
together and the section stays self-consistent.  Whether the model charges
correctly is asked of the model rather than of any one kernel, in
`tests/test_latency.py`, against hand-counted bytes, FLOPs and cycles.

What a section is for is the composition — which tensor dominates the traffic, what
the ratio to the kernel's declared footprint is, which unit the cycles land on.
Confirm that against what the kernel is supposed to do; a sentence in prose that
disagrees with the table below it does not survive review.  Every figure is
formatted to four significant digits, and nothing here varies between runs at fixed
parameters, so a diff means the cost changed."""

_SECTION = re.compile(
    r"^## (?P<name>[^\n]+)\n\n```text\n(?P<body>.*?)\n```\n", re.M | re.S)


def _sig(value: float, digits: int = 4) -> str:
    """Format to *digits* significant digits, without exponent noise for ints."""
    if value == 0:
        return "0"
    if isinstance(value, (int, np.integer)) or float(value).is_integer():
        return f"{int(value):,}"
    magnitude = math.floor(math.log10(abs(value)))
    decimals = max(0, digits - 1 - magnitude)
    return f"{value:,.{decimals}f}"


class ArgExtents:
    """Which declared argument a view origin belongs to.

    A distributed memory view is charged per partition, so one tensor arrives as
    several origins, and an origin belongs to the argument whose element extent
    contains it.  The output claims and the cost derivation both need that
    mapping and had a copy each — same construction, same tie-break, in two files
    whose drift would surface as a kernel writing to a tensor in one report and
    not in the other.

    An argument with no array behind it has no extent and is therefore never
    matched: the ring-reduce kernels take raw element indices rather than
    tensors, and a pointer with no length cannot contain anything.  Callers get
    ``None`` for those and must report them, not drop them.
    """

    def __init__(self, arg_ptrs: Dict[str, Any], tensors: Dict[str, Any]) -> None:
        self._extents: List[Tuple[int, int, str]] = []
        self._numel: Dict[str, int] = {}
        for name, ptr in arg_ptrs.items():
            value = tensors.get(name)
            n = int(value.size) if isinstance(value, np.ndarray) else 0
            if isinstance(ptr, int) and n:
                self._extents.append((ptr, ptr + n, name))
                self._numel[name] = n

    def of(self, target: Any) -> Optional[str]:
        """The argument *target* lies within, or ``None`` if no extent holds it."""
        if not isinstance(target, int):
            return None
        hit = [name for lo, hi, name in self._extents if lo <= target < hi]
        if not hit:
            return None
        # Narrowest extent wins: a tensor laid out inside another's address range
        # — which the hand-placed multi-tensor examples do — would match both.
        return min(hit, key=lambda nm: self._numel[nm])


def _fold_targets(report, arg_ptrs: Dict[str, Any],
                  tensors: Dict[str, Any], category: str
                  ) -> Tuple[List[Tuple[str, int, Dict[str, int]]], int]:
    """Attribute one transport's bytes to argument names.

    A distributed memory view is charged per partition, so one tensor arrives as
    several origins; an origin belongs to the argument whose element extent
    contains it.  Bytes that match no argument are returned separately and
    printed, never folded into a neighbour: a breakdown that silently drops a row
    adds up to less than the total while looking complete.
    """
    extents = ArgExtents(arg_ptrs, tensors)
    per_arg: Dict[str, Dict[str, Any]] = {}
    unattributed = 0
    for target, row in report.traffic_by_target(category).items():
        name = extents.of(target)
        if name is None:
            unattributed += row["nbytes"]
            continue
        slot = per_arg.setdefault(name, {"nbytes": 0, "ops": {}})
        slot["nbytes"] += row["nbytes"]
        for op, count in row["ops"].items():
            slot["ops"][op] = slot["ops"].get(op, 0) + count

    ordered = sorted(per_arg.items(), key=lambda kv: (-kv[1]["nbytes"], kv[0]))
    return [(name, slot["nbytes"], slot["ops"]) for name, slot in ordered], unattributed


def unique_bytes(tensors: Dict[str, Any]) -> int:
    """Bytes a kernel would move if it read and wrote each tensor exactly once.

    The denominator of ``traffic_ratio``.  Derived from the declared tensors
    rather than from the trace, so it is independent of how the kernel tiles its
    access — which is the point of comparing the two.  That independence is also
    why the ratio can land below 1: a kernel indexing into a tensor rather than
    sweeping it moves less than the tensor's whole footprint, and the ratio says
    so rather than being clamped.
    """
    total = 0
    for value in tensors.values():
        if isinstance(value, np.ndarray):
            total += int(value.nbytes)
    return total


def render_derivation(entry, ledger, params: Dict[str, Any]) -> str:
    """The committed text for one entry at one parameter set."""
    report = ledger.report
    if report is None:
        raise ValueError("no latency report — the kernel did not run")

    tensors = entry.build_tensors(params) if entry.tensors else {}
    # Re-deriving the tensors gives shapes and extents; the values are irrelevant
    # here and the factory is required to be deterministic at fixed parameters.
    arg_ptrs = ledger.arg_ptrs

    lines: List[str] = [f"kernel: {entry.name}   function: {entry.func}"]
    lines.append("parameters: " + ", ".join(
        f"{k}={v}" for k, v in sorted(params.items())))
    lines.append(f"grid cores active: {len(report.counters)}")
    lines.append("")

    hbm_total = sum(c.dram_bytes for c in report.counters.values())
    rows, unattributed = _fold_targets(report, arg_ptrs, tensors, "memory")
    lines.append(f"hbm_bytes = {hbm_total:,}")
    for name, nbytes, ops in rows:
        share = (nbytes / hbm_total * 100) if hbm_total else 0.0
        op_text = ", ".join(f"{op} x{count}" for op, count in sorted(ops.items()))
        lines.append(f"    {name:<18} {nbytes:>14,}  {share:5.1f}%   {op_text}")
    if unattributed:
        share = unattributed / hbm_total * 100 if hbm_total else 0.0
        lines.append(f"    {'<unattributed>':<18} {unattributed:>14,}  {share:5.1f}%   "
                     "origin did not fall inside any argument's extent")

    logical = unique_bytes(tensors)
    if logical:
        ratio = hbm_total / logical
        line = (f"unique_bytes = {logical:,}"
                f"    traffic_ratio = {_sig(ratio)}x")
        if ratio < 1:
            line += "    (below 1: the kernel reaches only part of a declared tensor)"
        lines.append(line)
    lines.append("")

    comm_total = sum(c.comm_bytes for c in report.counters.values())
    if comm_total:
        # Broken down by op rather than by argument. Cross-core traffic moves a
        # tile between cores; it has no origin in an HBM tensor, so asking which
        # argument moved it is the wrong question and answering "unattributed"
        # for all of it would imply a missing feature instead of a category error.
        lines.append(f"comm_bytes = {comm_total:,}")
        for op_type, count, nbytes in _comm_by_op(report):
            lines.append(f"    {op_type:<34} n={count:<6} {nbytes:>12,}")
        lines.append("")

    flops = sum(c.total_flops for c in report.counters.values())
    lines.append(f"flops = {flops:,}")
    if hbm_total:
        lines.append(f"arithmetic_intensity = flops / hbm_bytes = "
                     f"{flops:,} / {hbm_total:,} = {_sig(flops / hbm_total)}")
    lines.append("")

    critical = report.critical_core
    lines.append(f"kernel_cycles = {_sig(report.kernel_cycles)}"
                 f"    bottleneck = {report.bottleneck}")
    lines.append(f"    critical core   compute {_sig(critical.compute_cycles)}"
                 f"   memory {_sig(critical.memory_cycles)}"
                 f"   comm {_sig(critical.comm_cycles)}")
    for category, cycles in sorted(critical.cycles_by_category.items()):
        lines.append(f"    {category:<28} {_sig(cycles)}")
    lines.append("")

    lines.append("cycles charged per op type, critical core:")
    for op_type, count, cycles in _per_op(report, critical):
        lines.append(f"    {op_type:<34} n={count:<6} {_sig(cycles)}")
    lines.append("")

    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# The generated document
# ---------------------------------------------------------------------------

def read_sections(text: str) -> Dict[str, str]:
    """Every kernel's derivation in *text*, by kernel name."""
    return {m.group("name"): m.group("body") for m in _SECTION.finditer(text)}


def render_document(sections: Dict[str, str]) -> str:
    """The whole document, from a name -> derivation mapping.

    Ordered by name rather than by discovery, so adopting one kernel rewrites one
    section and a reordering never shows up as a diff.
    """
    parts = [TITLE, "", HEADER, "", PREAMBLE, ""]
    for name in sorted(sections):
        parts += [f"## {name}", "", "```text", sections[name], "```", ""]
    return "\n".join(parts).rstrip("\n") + "\n"


def update_document(path, name: str, body: str) -> bool:
    """Put *body* in as *name*'s section, leaving the others as committed.

    Returns whether anything changed.  Adopting one kernel must not depend on
    every other kernel having been run in the same invocation: the alternative is
    that a single-kernel ``adopt`` silently deletes seventeen sections.
    """
    existing = read_sections(path.read_text()) if path.exists() else {}
    if existing.get(name) == body:
        return False
    existing[name] = body
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_document(existing))
    return True


def _comm_by_op(report) -> List[Tuple[str, int, int]]:
    """Chip-wide cross-core bytes, by the op that moved them."""
    counts: Dict[str, int] = {}
    nbytes: Dict[str, int] = {}
    for counters in report.counters.values():
        for tentry in counters.trace or ():
            if tentry.category != "comm" or not tentry.nbytes:
                continue
            counts[tentry.op_type] = counts.get(tentry.op_type, 0) + 1
            nbytes[tentry.op_type] = nbytes.get(tentry.op_type, 0) + tentry.nbytes
    return sorted(((op, counts[op], nbytes[op]) for op in counts),
                  key=lambda row: (-row[2], row[0]))


def _per_op(report, core) -> List[Tuple[str, int, float]]:
    counts: Dict[str, int] = {}
    cycles: Dict[str, float] = {}
    for tentry in core.trace or ():
        counts[tentry.op_type] = counts.get(tentry.op_type, 0) + 1
        cycles[tentry.op_type] = cycles.get(tentry.op_type, 0.0) + tentry.cycles
    return sorted(((op, counts[op], cycles[op]) for op in counts),
                  key=lambda row: (-row[2], row[0]))
