// Copyright 2025 The Torch-Spyre Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License").
//
//! REAL-MODEL end-to-end — hermetic w.r.t. the scratchy `.cache`.
//!
//! Each test runs a real forward of a real model: the KTIR *program* is vendored
//! in-repo (`tests/fixtures/<model>/` — `manifest.json` + `node*.mlir`, no
//! weights), and the *weights* are fetched from a PUBLIC HuggingFace repo (no
//! `HF_TOKEN`) via `hf-hub` and read with the `safetensors` crate. Nothing reads
//! `~/.cache/cudaforge`.
//!
//! Correctness is checked against a REAL-MODEL GOLDEN: the production path
//! (`execute_segmented` — fuse + GPU/AMX offload + head-parallel attention) must
//! reproduce the `transformers` logits (vendored as `golden.f16.gz`, regenerated by
//! `tests/fixtures/gen_golden.py`). The per-row next-token argmax must match the
//! real model; `max_abs` is reported and loosely bounded (f16 over many layers vs
//! an f32 golden drifts). This catches fusion/offload/marshal/weight-layout bugs.
//!
//! Weights are PyTorch linear weights (`[out,in]`), bound VERBATIM / zero-copy as
//! f16 — NO transpose at load. The KTIR program contracts the correct axis itself
//! (`matmul_transpose_b`). Runtime activations the program expects but that aren't
//! HF weights — the input activation (`role:embed`), RoPE `cos`/`sin`, the (empty)
//! KV-cache `prefix_k`/`prefix_v`, and the attention mask — come from the vendored
//! `t<id>.f16.gz` the generator wrote from the same model forward.
//!
//! NOT `#[ignore]` / NOT env-gated: runs in default `cargo test`. Weights are
//! fetched from HF (content-addressed, cached). Prefill (m>1) is `cfg(metal)` —
//! the fused [1,1] segments need the offload for full-M reconstruction.

#![cfg(feature = "optimizer")]

use ktir_emulator::dtypes::DType;
use ktir_emulator::interpreter::Arg;
use ktir_emulator::ir::IRModule;
use ktir_emulator::parser::parse_module;
use ktir_optimizer::fusion::{Binding, NodeSpec, ProgramSpec};
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};

/// Resolve a vendored fixture to a directory of files (`manifest.json`,
/// `node*.mlir`, `t<id>.f16.gz`, `golden.f16.gz`).
///
/// Fixtures are committed as one `tests/fixtures/<name>.tar.gz` per model×config
/// (4 archives instead of the ~1.6k loose dump files that bloated the diff). This
/// unpacks the archive ONCE into the cargo target tmp dir and hands back that
/// path, so every downstream read (`dir.join(...)`) is unchanged. An already
/// unpacked `tests/fixtures/<name>/` — e.g. freshly written by `gen_golden.py`,
/// or `tar xzf`'d for local work — is preferred as-is (and is gitignored).
fn fixture_dir(name: &str) -> PathBuf {
    static CACHE: OnceLock<Mutex<HashMap<String, PathBuf>>> = OnceLock::new();
    let mut cache = CACHE
        .get_or_init(|| Mutex::new(HashMap::new()))
        .lock()
        .unwrap();
    if let Some(dir) = cache.get(name) {
        return dir.clone();
    }

    let fixtures = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    let unpacked = fixtures.join(name);
    let dir = if unpacked.join("manifest.json").is_file() {
        unpacked
    } else {
        // Unpack into the (per-target, cargo-managed) tmp dir, once. Re-run /
        // parallel safe: a fully populated `dest` (manifest present) is reused;
        // otherwise we extract into a unique temp dir and ATOMICALLY rename it
        // into place. We never mutate `dest` in situ — so a second test run, a
        // concurrent `cargo test`, or a crashed prior extraction can't observe a
        // half-written fixture or clobber one another.
        // `CARGO_TARGET_TMPDIR` (set for integration tests) is a compile-time var,
        // so read it with `env!`, not at runtime — keeps extraction under
        // `target/tmp/` (cleaned by `cargo clean`) rather than leaking to /tmp.
        let base = Path::new(env!("CARGO_TARGET_TMPDIR")).join("ktir-fixtures");
        let dest = base.join(name);
        if !dest.join("manifest.json").is_file() {
            let archive = fixtures.join(format!("{name}.tar.gz"));
            let file = std::fs::File::open(&archive)
                .unwrap_or_else(|e| panic!("open fixture archive {archive:?}: {e}"));
            let tmp = base.join(format!(".incoming-{name}-{}", std::process::id()));
            let _ = std::fs::remove_dir_all(&tmp);
            std::fs::create_dir_all(&tmp).unwrap();
            tar::Archive::new(flate2::read::GzDecoder::new(file))
                .unpack(&tmp)
                .unwrap_or_else(|e| panic!("unpack {archive:?}: {e}"));
            // Publish atomically. If another writer won the race, `dest` is
            // already complete (rename onto a non-empty dir fails) — drop our temp.
            if std::fs::rename(&tmp, &dest).is_err() {
                let _ = std::fs::remove_dir_all(&tmp);
            }
        }
        dest
    };
    cache.insert(name.to_string(), dir.clone());
    dir
}

/// Hermetic (no network, no GPU): every vendored fixture archive unpacks and
/// every `node*.mlir` it references parses. Guards the tar.gz vendoring scheme
/// itself, independent of the weight-fetching real-forward tests below.
#[test]
fn fixtures_unpack_and_parse() {
    for name in [
        "smollm2-135m",
        "smollm2-135m-prefill",
        "llama-3.2-1b",
        "llama-3.2-1b-prefill",
    ] {
        let dir = fixture_dir(name);
        assert!(
            dir.join("golden.f16.gz").is_file(),
            "{name}: golden.f16.gz missing after unpack"
        );
        // Parses manifest.json + every node*.mlir; panics on any corruption.
        let _ = load_program(&dir);
    }
}

/// Read a gzip'd, headerless, row-major little-endian **f16** `.f16.gz` (the
/// vendored golden / runtime-input convention written by `gen_golden.py`) and
/// widen to f32. f16 because Spyre runs f16 (the program is f16, so f32 storage is
/// needless and the `max_abs` band is looser than f16); gzip -9 because the
/// constant tensors (zero KV-prefix, identity cos/sin, all-masked mask) compress to
/// ~nothing.
fn read_f16_gz(path: &Path) -> Vec<f32> {
    use std::io::Read;
    let file = std::fs::File::open(path).unwrap_or_else(|e| panic!("open {path:?}: {e}"));
    let mut bytes = Vec::new();
    flate2::read::GzDecoder::new(file)
        .read_to_end(&mut bytes)
        .unwrap_or_else(|e| panic!("gunzip {path:?}: {e}"));
    ktir_emulator::codec::decode(&bytes, bytes.len() / 2, DType::F16)
}

/// CI runs all smollm2 tests + the llama PREFILL golden only. The other heavy llama
/// tests self-skip when `CI` is set (GitHub Actions sets it automatically), since each
/// takes ~100-270s on the GPU-less CI runner for coverage smollm2 already gives. Unset
/// in a normal local shell ⇒ everything runs.
fn skip_heavy_llama_in_ci() -> bool {
    if std::env::var_os("CI").is_some() {
        eprintln!("CI set — skipping heavy llama test (smollm2 covers this path)");
        return true;
    }
    false
}

fn argmax(v: &[f32]) -> usize {
    v.iter()
        .enumerate()
        .fold((0, f32::NEG_INFINITY), |(bi, bv), (i, &x)| {
            if x > bv { (i, x) } else { (bi, bv) }
        })
        .0
}

/// A vendored program: module + spec + the metadata to marshal sources.
struct Program {
    module: IRModule,
    spec: ProgramSpec,
    /// tensor id -> (rows, cols)
    shape: HashMap<u64, (usize, usize)>,
    /// source id -> (role, optional HF disk-name) from manifest `sources[]`
    src_meta: HashMap<u64, (String, Option<String>)>,
    is_source: HashSet<u64>,
    mask_id: Option<u64>,
    result_id: u64,
}

fn load_program(dir: &Path) -> Program {
    let manifest: serde_json::Value =
        serde_json::from_slice(&std::fs::read(dir.join("manifest.json")).unwrap()).unwrap();

    let mut shape = HashMap::new();
    let mut is_source = HashSet::new();
    for t in manifest["tensors"].as_array().unwrap() {
        let id = t["id"].as_u64().unwrap();
        shape.insert(
            id,
            (
                t["rows"].as_u64().unwrap() as usize,
                t["cols"].as_u64().unwrap() as usize,
            ),
        );
        if t["is_source"].as_bool().unwrap_or(false) {
            is_source.insert(id);
        }
    }
    let mut src_meta = HashMap::new();
    for s in manifest["sources"].as_array().unwrap() {
        let id = s["id"].as_u64().unwrap();
        let role = s["role"].as_str().unwrap_or("weight").to_string();
        let disk = s["disk"].as_str().map(|x| x.to_string());
        src_meta.insert(id, (role, disk));
    }
    let result_id = manifest["result"].as_u64().unwrap();
    let mask_id = manifest["attn_mask"].as_u64();

    let mut sources: HashSet<u64> = is_source.clone();
    if let Some(m) = mask_id {
        sources.insert(m);
    }

    let mut module = IRModule::default();
    let mut nodes = Vec::new();
    for node in manifest["nodes"].as_array().unwrap() {
        let func = node["fn"].as_str().unwrap().to_string();
        let mlir = node["mlir"].as_str().unwrap();
        let parsed = parse_module(&std::fs::read_to_string(dir.join(mlir)).unwrap())
            .unwrap_or_else(|e| panic!("parse {mlir}: {e}"));
        for (_, f) in parsed.functions {
            module.add_function(f);
        }
        let bindings = node["args"]
            .as_array()
            .unwrap()
            .iter()
            .map(|a| Binding {
                arg: format!("%{}", a["name"].as_str().unwrap()),
                tensor: a["tensor"].as_u64().unwrap(),
                is_output: a["is_output"].as_bool().unwrap_or(false),
            })
            .collect();
        nodes.push(NodeSpec { func, bindings });
    }
    let spec = ProgramSpec {
        nodes,
        sources,
        results: HashSet::from([result_id]),
    };
    Program {
        module,
        spec,
        shape,
        src_meta,
        is_source,
        mask_id,
        result_id,
    }
}

// ---------------------------------------------------------------------------
// Real weights from a public HF repo (no token) via hf-hub + safetensors.
// ---------------------------------------------------------------------------

/// Open a repo's safetensors as a `name -> bf16 f16-bytes` resolver. Handles
/// single-file (`model.safetensors`) and sharded (`*.index.json`) layouts.
struct Weights {
    /// tensor name -> f16 bytes already converted from bf16 (verbatim PyTorch `[out,in]`,
    /// bound zero-copy — the program's `matmul_transpose_b` reads this layout directly).
    f16: HashMap<String, Vec<u8>>,
}

impl Weights {
    /// Returns `None` (skip the test) if the repo can't be fetched (offline /
    /// HF down) — so a network-less box degrades gracefully rather than failing
    /// spuriously; a box WITH network exercises the real path.
    fn fetch(repo: &str) -> Option<Weights> {
        let api = hf_hub::api::sync::Api::new().ok()?;
        let model = api.model(repo.to_string());

        // Collect the safetensors shard filenames.
        let shard_files: Vec<String> = match model.get("model.safetensors.index.json") {
            Ok(idx) => {
                let j: serde_json::Value =
                    serde_json::from_slice(&std::fs::read(idx).ok()?).ok()?;
                let mut set = std::collections::BTreeSet::new();
                for v in j["weight_map"].as_object()?.values() {
                    set.insert(v.as_str()?.to_string());
                }
                set.into_iter().collect()
            }
            Err(_) => vec!["model.safetensors".to_string()],
        };

        let t_dl = std::time::Instant::now();
        let mut blobs = Vec::new();
        for f in &shard_files {
            let path = model.get(f).ok()?; // cached → ~free; cache-miss → network
            blobs.push(std::fs::read(path).ok()?);
        }
        let dl_s = t_dl.elapsed().as_secs_f64();
        let dl_mb = blobs.iter().map(|b| b.len()).sum::<usize>() as f64 / 1e6;
        // Eagerly convert every tensor's bf16 bytes -> f16 bytes (the stick
        // layout). bf16 is the on-disk dtype for these models.
        let t_cv = std::time::Instant::now();
        let mut f16 = HashMap::new();
        // Consume each shard by value and drop it right after converting, so the
        // ~2.5 GB of bf16 bytes are freed instead of staying resident behind the
        // f16 map for the whole forward. (Keeping them alive was the e2e's peak-RSS
        // hog → swap thrashing on the 7 GB macOS runner; not an emulator issue.)
        for b in blobs.drain(..) {
            let st = safetensors::SafeTensors::deserialize(&b).ok()?;
            for (name, view) in st.tensors() {
                let raw = view.data();
                let n = raw.len() / 2;
                // bf16 LE bytes -> f16 LE bytes via the crate codec.
                let as_f16 = ktir_emulator::codec::bf16_to_f16(raw, n);
                f16.insert(name.to_string(), as_f16);
            }
        }
        let cv_s = t_cv.elapsed().as_secs_f64();
        eprintln!(
            "  [Weights::fetch {repo}: get+read {dl_mb:.0} MB in {dl_s:.1}s, bf16->f16 convert {cv_s:.1}s]"
        );
        Some(Weights { f16 })
    }

    /// Verbatim f16 bytes for `<disk>.weight` in PyTorch `[out,in]` order — bound
    /// zero-copy, NO transpose. The KTIR program is responsible for contracting the
    /// correct axis (via `matmul_transpose_b`). Tied lm_head falls back to
    /// `embed_tokens.weight`.
    fn weight(&self, disk: &str) -> Option<&[u8]> {
        if let Some(v) = self.f16.get(&format!("{disk}.weight")) {
            return Some(v);
        }
        if disk == "lm_head" {
            return self
                .f16
                .get("model.embed_tokens.weight")
                .map(|v| v.as_slice());
        }
        None
    }
}

/// Deterministic synthetic activation for a non-weight source, used only as a
/// pre-generation fallback when a vendored `t<id>.f16.gz` is absent. RoPE-valid
/// (cos=1, sin=0 = identity rotation) so the forward stays finite.
fn synth(role: &str, n: usize) -> Vec<f32> {
    match role {
        "cos" => vec![1.0; n],
        "sin" => vec![0.0; n],
        // input activation / KV-cache prefixes: small bounded deterministic.
        _ => (0..n).map(|i| ((i % 17) as f32 - 8.0) * 0.01).collect(),
    }
}

/// Build the source args (keyed `t{id}`). Real f16 weights from HF; the runtime
/// activations (input activation, RoPE cos/sin, KV prefix) come from the VENDORED
/// `t<id>.f16.gz` the generator wrote from the real model forward, so production is
/// fed exactly what the `golden.f16.gz` was computed against. (A missing file falls
/// back to a deterministic synth so the loader still runs pre-generation.)
fn build_args(dir: &Path, p: &Program, w: &Weights) -> Vec<(String, Arg)> {
    let mut args = Vec::new();
    let mut ids: Vec<u64> = p.is_source.iter().copied().collect();
    if let Some(m) = p.mask_id
        && !ids.contains(&m)
    {
        ids.push(m);
    }
    ids.sort_unstable();
    let m_valid = p
        .src_meta
        .iter()
        .find(|(_, (role, _))| role == "embed")
        .map(|(id, _)| p.shape[id].0)
        .unwrap_or(1);
    for id in ids {
        let (rows, cols) = p.shape[&id];
        let n = rows * cols;
        let key = format!("t{id}");
        let vendored = dir.join(format!("t{id}.f16.gz"));

        // Weight sources: always from HF (verbatim f16 bytes).
        if let Some((_, Some(d))) = p.src_meta.get(&id) {
            let bytes = w
                .weight(d)
                .unwrap_or_else(|| panic!("HF weight {d:?} (t{id}) not found in repo"));
            assert_eq!(
                bytes.len(),
                n * 2,
                "weight {d} (t{id}) numel {} != {n}",
                bytes.len() / 2
            );
            args.push((
                key,
                Arg::TensorBytes {
                    data: bytes.to_vec(),
                    shape: vec![rows, cols],
                    dtype: DType::F16,
                },
            ));
            continue;
        }

        // Runtime activations: prefer the vendored real tensor (generated from the
        // model forward); else fall back to a deterministic synth.
        let data = if vendored.is_file() {
            let v = read_f16_gz(&vendored);
            assert_eq!(v.len(), n, "vendored t{id} len {} != {n}", v.len());
            v
        } else if Some(id) == p.mask_id {
            // The mask applies to the 64-position prefix KV CACHE, which is EMPTY
            // for a fresh forward (the current token(s) enter via a separate fresh
            // K/V path, not through this mask). So mask ALL prefix positions (f16-min
            // additive ≈ -inf) — attention then uses only the fresh tokens.
            let _ = m_valid;
            vec![-65504.0; n]
        } else {
            let role = p
                .src_meta
                .get(&id)
                .map(|(r, _)| r.as_str())
                .unwrap_or("weight");
            match role {
                "prefix_k" | "prefix_v" => vec![0.0; n],
                _ => synth(role, n),
            }
        };
        args.push((
            key,
            Arg::Tensor {
                data,
                shape: vec![rows, cols],
                dtype: DType::F16,
            },
        ));
    }
    args
}

/// Production path: the real serving API — fuse into ordered segments and run
/// each (fused [1,1] GPU/AMX offload + native head-parallel attention).
///
/// `last_token`: when true (and on Metal), the final lm_head projection computes
/// ONLY the last token's logits (`[1, vocab]`) — the production generation default,
/// since autoregressive sampling reads only the last position. The returned buffer
/// is still `[m, vocab]`-sized but only its last row is populated. When false it
/// computes ALL m rows (the comprehensive all-rows correctness path).
fn forward_production(p: &Program, args: &[(String, Arg)], last_token: bool) -> Vec<f32> {
    let refs: Vec<(&str, Arg)> = args.iter().map(|(n, a)| (n.as_str(), a.clone())).collect();
    let key = format!("t{}", p.result_id);
    // RESIDENT (weights marshaled ONCE into one persistent HBM, kernels chained
    // on-device, no per-segment host round-trip) is the fast path ON METAL — it
    // avoids re-encoding/decoding ~2.5 GB per segment × ~178 segments per pass.
    //
    // OFF METAL (Linux CI) there is no GPU HBM to stay resident in and the GEMM
    // offload can't reach NAX/AMX, so the resident path runs the K-loop GEMMs
    // through the interpreter and is ~2× SLOWER than the segmented path there
    // (it doubled the Linux e2e: 11 → 21 min). The segmented path routes each
    // matmul tile to OpenBLAS, so use it off-Metal. Both reproduce the golden.
    #[cfg(metal)]
    let out = {
        let mut exec = ktir_emulator::resident::ResidentExecutor::new(p.module.clone(), &p.spec)
            .expect("build resident executor");
        exec.set_sources(&refs).expect("marshal sources");
        exec.set_last_token_only(last_token);
        exec.run(&[&key]).expect("execute_resident")
    };
    #[cfg(not(metal))]
    let out = {
        let _ = last_token; // last-token pruning is the Metal resident path only
        ktir_emulator::segmented::execute_segmented(&p.module, &p.spec, &refs, &[&key])
            .expect("execute_segmented")
    };
    out.get(&key).expect("result").data.clone()
}

/// Run a real model forward and assert the production output matches the
/// REAL-MODEL golden (transformers logits, vendored as `golden.f16.gz` by
/// `gen_golden.py`). Skips if the golden isn't present (not generated) or the repo
/// can't be fetched (offline). The primary check is the next-token argmax of the
/// last row; `max_abs` is reported and bounded (f16 over many layers vs an f32
/// golden drifts, so the band is loose — argmax is the real assertion).
fn real_forward_golden(fixture: &str, repo: &str) {
    let dir = fixture_dir(fixture);
    if !dir.join("golden.f16.gz").is_file() {
        eprintln!(
            "{fixture}: no vendored golden.f16.gz (run tests/fixtures/gen_golden.py) — skipping"
        );
        return;
    }
    let p = load_program(&dir);
    let t_fetch = std::time::Instant::now();
    let Some(w) = Weights::fetch(repo) else {
        eprintln!("{fixture}: could not fetch {repo} (offline?) — skipping");
        return;
    };
    let fetch_s = t_fetch.elapsed().as_secs_f64();
    let args = build_args(&dir, &p, &w);
    let t_fwd = std::time::Instant::now();
    // ALL-ROWS path: compute every token position so the per-row argmax check below
    // validates the whole forward (a stricter probe than production needs). The
    // last-token production default is validated separately by
    // `real_forward_golden_last_token`.
    let prod = forward_production(&p, &args, false);
    let fwd_s = t_fwd.elapsed().as_secs_f64();
    eprint!("{}", ktir_emulator::interpreter::profile_report()); // KTIR_PROFILE=1
    let golden = read_f16_gz(&dir.join("golden.f16.gz"));

    assert_eq!(
        prod.len(),
        golden.len(),
        "{fixture}: result {} != golden {}",
        prod.len(),
        golden.len()
    );
    assert!(
        prod.iter().all(|x| x.is_finite()),
        "{fixture}: non-finite production output"
    );

    let (m, vocab) = p.shape[&p.result_id];
    assert_eq!(m * vocab, prod.len(), "{fixture}: result shape {m}x{vocab}");
    // The emulator's next-token pick must be one the real model also ranked at
    // the very top: its GOLDEN logit must be within `tol` of the golden max.
    // Exact argmax is too strict when the model's top tokens are near-tied — the
    // smollm2 prompt's top-5 sit within ~0.5 logits (a 0.16 margin) — so harmless
    // cross-platform f16 drift (~0.3 on macOS Accelerate, ~1.0 on Linux OpenBLAS,
    // over ~30 f16 layers vs an f32 golden) flips the pick to an equally-valid
    // neighbour. `tol` must clear the worst-case gap drift alone can open:
    // pick = argmax(prod) ⇒ golden[pick] ≥ golden_max − 2·max_abs, so the gap can
    // reach 2·max_abs (≈2.1 for the observed Linux max_abs ≈ 1.05). 3.0 covers it
    // with headroom; a genuinely broken forward has a far larger max_abs and still
    // fails; a confident model (llama) keeps this ~exact (its pick gap is ~0).
    const ARGMAX_LOGIT_TOL: f32 = 3.0;
    let mut argmax_hits = 0usize;
    for r in 0..m {
        let row = r * vocab..(r + 1) * vocab;
        let g = &golden[row.clone()];
        let pred = argmax(&prod[row]);
        let g_max = g.iter().copied().fold(f32::NEG_INFINITY, f32::max);
        if g_max - g[pred] <= ARGMAX_LOGIT_TOL {
            argmax_hits += 1;
        }
    }
    let max_abs = prod
        .iter()
        .zip(&golden)
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f32, f32::max);
    eprintln!(
        "{fixture} via {repo}: [{m},{vocab}] logits, {argmax_hits}/{m} rows pick a top token \
         (within {ARGMAX_LOGIT_TOL} logits of the model's best), max abs diff {max_abs:.4} \
         [weights {fetch_s:.1}s, forward {fwd_s:.1}s]"
    );
    assert_eq!(
        argmax_hits, m,
        "{fixture}: next-token prediction is not within {ARGMAX_LOGIT_TOL} logits of the real model's top token"
    );
    // f16 over ~30 layers vs an f32 golden drifts more on Linux OpenBLAS (~1.05)
    // than on macOS Accelerate (~0.27) — different f32 accumulation order. The
    // band is loose because the per-row argmax above is the meaningful check; this
    // only catches a grossly broken forward (max_abs would be far larger / NaN).
    assert!(
        max_abs < 2.0,
        "{fixture}: logits diverge from golden by {max_abs}"
    );
}

#[test]
fn smollm2_135m_decode_real_forward() {
    real_forward_golden("smollm2-135m", "HuggingFaceTB/SmolLM2-135M");
}

#[test]
fn llama_3_2_1b_decode_real_forward() {
    if skip_heavy_llama_in_ci() {
        return;
    }
    real_forward_golden("llama-3.2-1b", "unsloth/Llama-3.2-1B-Instruct");
}

// PREFILL (m>1) requires `cfg(metal)`: the fused [1,1] segments need the GPU/AMX
// offload for full-M reconstruction (without it they compute only row 0). Run with
// `--features metal`.
#[cfg(metal)]
#[test]
fn smollm2_135m_prefill_real_forward() {
    real_forward_golden("smollm2-135m-prefill", "HuggingFaceTB/SmolLM2-135M");
}

#[cfg(metal)]
#[test]
fn llama_3_2_1b_prefill_real_forward() {
    real_forward_golden("llama-3.2-1b-prefill", "unsloth/Llama-3.2-1B-Instruct");
}

/// LAST-TOKEN golden: the PRODUCTION generation default — the lm_head computes only
/// the LAST token's logits — must still pick the real model's next token. This is the
/// correctness gate that justifies last-token mode being ON by default in the resident
/// production path (`execute_resident`): identical next-token prediction, ~1/m the
/// lm_head work. Mirrors [`real_forward_golden`] but asserts on the LAST row only (the
/// other rows are intentionally not computed in this mode). Prefill-only / `cfg(metal)`
/// (the rewrite is the resident GPU path; decode is m=1 so all-rows == last-token).
#[cfg(metal)]
fn real_forward_golden_last_token(fixture: &str, repo: &str) {
    let dir = fixture_dir(fixture);
    if !dir.join("golden.f16.gz").is_file() {
        eprintln!("{fixture}: no vendored golden.f16.gz — skipping");
        return;
    }
    let p = load_program(&dir);
    let Some(w) = Weights::fetch(repo) else {
        eprintln!("{fixture}: could not fetch {repo} (offline?) — skipping");
        return;
    };
    let args = build_args(&dir, &p, &w);
    // LAST-TOKEN production path: only row m-1 of the logits is computed.
    let prod = forward_production(&p, &args, true);
    let golden = read_f16_gz(&dir.join("golden.f16.gz"));
    let (m, vocab) = p.shape[&p.result_id];
    assert_eq!(prod.len(), golden.len(), "{fixture}: result/golden length");
    // Only the LAST row is computed in last-token mode — check exactly that row.
    const ARGMAX_LOGIT_TOL: f32 = 3.0;
    let r = m - 1;
    let row = r * vocab..(r + 1) * vocab;
    let pred_row = &prod[row.clone()];
    assert!(
        pred_row.iter().all(|x| x.is_finite()),
        "{fixture}: non-finite last-token logits"
    );
    let g = &golden[row];
    let pred = argmax(pred_row);
    let g_max = g.iter().copied().fold(f32::NEG_INFINITY, f32::max);
    let max_abs = pred_row
        .iter()
        .zip(g)
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f32, f32::max);
    eprintln!(
        "{fixture} via {repo} [LAST-TOKEN]: last row [{vocab}] picks {} (golden gap {:.4}), \
         max abs diff {max_abs:.4}",
        pred,
        g_max - g[pred]
    );
    assert!(
        g_max - g[pred] <= ARGMAX_LOGIT_TOL,
        "{fixture}: last-token next-token prediction is not within {ARGMAX_LOGIT_TOL} logits \
         of the real model's top token"
    );
    assert!(
        max_abs < 2.0,
        "{fixture}: last-token last-row logits diverge from golden by {max_abs}"
    );
}

#[cfg(metal)]
#[test]
fn smollm2_135m_prefill_last_token_real_forward() {
    real_forward_golden_last_token("smollm2-135m-prefill", "HuggingFaceTB/SmolLM2-135M");
}

#[cfg(metal)]
#[test]
fn llama_3_2_1b_prefill_last_token_real_forward() {
    if skip_heavy_llama_in_ci() {
        return;
    }
    real_forward_golden_last_token("llama-3.2-1b-prefill", "unsloth/Llama-3.2-1B-Instruct");
}

// ---------------------------------------------------------------------------
// WHOLE-PREFILL e2e WALL-CLOCK A/B: the optimizer (head re-roll + flash, applied
// at the execution entry) vs the unoptimized baseline (`KTIR_NO_ATTENTION_REWRITE`),
// on the SAME real program / weights / inputs the golden test uses. Reports
// best-of-N wall-clock for both and asserts the optimized output is argmax-faithful
// to the baseline (so the speedup is real, not a correctness shortcut). `#[ignore]`
// (heavy + needs HF weights); run: `--release --features metal --ignored --nocapture`.
// ---------------------------------------------------------------------------

#[cfg(metal)]
fn time_prefill_opt_vs_baseline(fixture: &str, repo: &str) {
    let dir = fixture_dir(fixture);
    if !dir.join("golden.f16.gz").is_file() {
        eprintln!("{fixture}: no vendored golden.f16.gz — skipping");
        return;
    }
    let p = load_program(&dir);
    let Some(w) = Weights::fetch(repo) else {
        eprintln!("{fixture}: could not fetch {repo} (offline?) — skipping");
        return;
    };
    let args = build_args(&dir, &p, &w);
    let refs: Vec<(&str, Arg)> = args.iter().map(|(n, a)| (n.as_str(), a.clone())).collect();
    let key = format!("t{}", p.result_id);
    let runs = 3;

    let run_once = || {
        let t = std::time::Instant::now();
        let out = ktir_emulator::segmented::execute_segmented(&p.module, &p.spec, &refs, &[&key])
            .expect("execute_segmented");
        let ms = t.elapsed().as_secs_f64() * 1000.0;
        (out.get(&key).expect("result").data.clone(), ms)
    };

    // BASELINE: rewrites disabled (raw unrolled per-query-row attention).
    unsafe { std::env::set_var("KTIR_NO_ATTENTION_REWRITE", "1") };
    let mut base_ms = f64::INFINITY;
    let mut base_out = Vec::new();
    for _ in 0..runs {
        let (o, ms) = run_once();
        base_ms = base_ms.min(ms);
        base_out = o;
    }
    // OPTIMIZED: rewrites on (the default production path).
    unsafe { std::env::remove_var("KTIR_NO_ATTENTION_REWRITE") };
    let mut opt_ms = f64::INFINITY;
    let mut opt_out = Vec::new();
    for _ in 0..runs {
        let (o, ms) = run_once();
        opt_ms = opt_ms.min(ms);
        opt_out = o;
    }

    let (m, vocab) = p.shape[&p.result_id];
    let mut hits = 0usize;
    for r in 0..m {
        let row = r * vocab..(r + 1) * vocab;
        if argmax(&base_out[row.clone()]) == argmax(&opt_out[row]) {
            hits += 1;
        }
    }
    let max_abs = base_out
        .iter()
        .zip(&opt_out)
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f32, f32::max);
    eprintln!(
        "{fixture}: WHOLE-PREFILL e2e best-of-{runs}  baseline(no-rewrite) {base_ms:.1} ms | \
         optimized {opt_ms:.1} ms | {:.2}x   (opt-vs-base argmax {hits}/{m} match, max-abs {max_abs:.4})",
        base_ms / opt_ms
    );
    assert_eq!(
        hits, m,
        "{fixture}: optimized argmax diverges from the baseline"
    );
}

#[cfg(metal)]
#[test]
#[ignore = "real-model whole-prefill wall-clock A/B (optimized vs baseline); needs metal + HF weights; run --release --ignored --nocapture"]
fn time_smollm2_135m_prefill() {
    time_prefill_opt_vs_baseline("smollm2-135m-prefill", "HuggingFaceTB/SmolLM2-135M");
}

#[cfg(metal)]
#[test]
#[ignore = "real-model whole-prefill wall-clock A/B (optimized vs baseline); needs metal + HF weights; run --release --ignored --nocapture"]
fn time_llama_3_2_1b_prefill() {
    time_prefill_opt_vs_baseline("llama-3.2-1b-prefill", "unsloth/Llama-3.2-1B-Instruct");
}

// ---------------------------------------------------------------------------
// HERMETIC E2E PERF — whole-model ms/pass through the production RESIDENT path
// (`resident::ResidentExecutor`: weights marshaled ONCE into one persistent HBM,
// segments chained on-device, NO per-pass re-marshal), on the SAME vendored
// fixtures + public HF weights the golden tests use — NO `~/.cache/cudaforge`
// bundle. This is the RUST side of PERFORMANCE.md's "E2E whole-model" table; the
// PYTHON side is `tests/fixtures/bench_e2e_hermetic.py` (the per-node reference
// interpreter on the same fixtures + HF weights). best-of-N median, one warm-up
// pass excluded; ITERS env overrides the pass count (default 5). `#[ignore]`
// (heavy + needs HF weights); run: `--release --ignored --nocapture --test-threads=1`.
// ---------------------------------------------------------------------------
#[cfg(metal)]
fn time_resident_e2e(fixture: &str, repo: &str) {
    let dir = fixture_dir(fixture);
    if !dir.join("manifest.json").is_file() {
        eprintln!("{fixture}: no fixture manifest — skipping");
        return;
    }
    let p = load_program(&dir);
    let Some(w) = Weights::fetch(repo) else {
        eprintln!("{fixture}: could not fetch {repo} (offline?) — skipping");
        return;
    };
    let args = build_args(&dir, &p, &w);
    let refs: Vec<(&str, Arg)> = args.iter().map(|(n, a)| (n.as_str(), a.clone())).collect();
    let key = format!("t{}", p.result_id);
    let iters: usize = std::env::var("ITERS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(5);

    // Resident contract: build the executor + marshal weights ONCE, OUTSIDE the
    // timed loop; the multi-pass loop re-uploads NOTHING.
    let mut exec = ktir_emulator::resident::ResidentExecutor::new(p.module.clone(), &p.spec)
        .expect("build resident executor");
    exec.set_sources(&refs).expect("marshal weights once");
    exec.run(&[&key]).expect("warmup"); // excluded

    let mut times: Vec<f64> = Vec::with_capacity(iters);
    for _ in 0..iters {
        let t = std::time::Instant::now();
        exec.run(&[&key]).expect("timed resident run");
        times.push(t.elapsed().as_secs_f64() * 1e3);
    }
    times.sort_by(|a, b| a.partial_cmp(b).unwrap());
    let median = times[times.len() / 2];
    let (m, _vocab) = p.shape[&p.result_id];
    eprintln!("{fixture} e2e (Rust RESIDENT): {median:.1} ms/pass  (m={m}, {iters} passes)");
    eprint!("{}", ktir_emulator::interpreter::profile_report()); // KTIR_PROFILE=1
}

/// REGRESSION GUARD for the multi-step decode path the single-pass golden tests do
/// NOT cover: scratchy's vllm loop calls `set_sources` + `run` every token, so the
/// resident weight cache must survive across `set_sources` calls AND never serve a
/// stale buffer. This builds ONE executor, runs, calls `set_sources` again (as the
/// decode loop does), runs again, and asserts the output equals a FRESH executor's
/// output for the same sources. A weight-cache bug (keeping a stale/wrong buffer
/// across `set_sources`) makes the second run diverge — invisible to the one-shot
/// golden. Default `#[test]` (cfg(metal)); small fixture for speed.
#[cfg(metal)]
#[test]
fn resident_multistep_set_sources_stable() {
    let dir = fixture_dir("smollm2-135m");
    if !dir.join("manifest.json").is_file() || !dir.join("golden.f16.gz").is_file() {
        eprintln!("smollm2-135m: fixture absent — skipping");
        return;
    }
    let p = load_program(&dir);
    let Some(w) = Weights::fetch("HuggingFaceTB/SmolLM2-135M") else {
        eprintln!("offline — skipping");
        return;
    };
    let args = build_args(&dir, &p, &w);
    let key = format!("t{}", p.result_id);
    let read = |out: &std::collections::HashMap<String, ktir_emulator::interpreter::Output>| {
        out.get(&key).expect("result").data.clone()
    };
    // A PERTURBED copy of the input activation (the `embed` source, t0): a different
    // "token". Decode threads a new one each step, so the kept constant weights must
    // produce the SAME result for it as a fresh executor — while the KV cache (a
    // forward-written tid) is correctly re-read, not served stale.
    let perturb = |a: &Arg| -> Arg {
        match a {
            Arg::Tensor { data, shape, dtype } => Arg::Tensor {
                data: data.iter().map(|x| x * 0.5 + 0.01).collect(),
                shape: shape.clone(),
                dtype: *dtype,
            },
            other => other.clone(),
        }
    };
    let input_name = "t0"; // manifest: id 0, role `embed` — the per-step input.
    let refs_a: Vec<(&str, Arg)> = args.iter().map(|(n, a)| (n.as_str(), a.clone())).collect();
    let refs_b: Vec<(&str, Arg)> = args
        .iter()
        .map(|(n, a)| {
            (
                n.as_str(),
                if n == input_name {
                    perturb(a)
                } else {
                    a.clone()
                },
            )
        })
        .collect();
    let input_b: Vec<(&str, Arg)> = refs_b
        .iter()
        .filter(|(n, _)| *n == input_name)
        .map(|(n, a)| (*n, a.clone()))
        .collect();
    assert!(!input_b.is_empty(), "input source t0 not found in args");

    // FRESH executor with input B — the reference for the perturbed input.
    let mut fresh =
        ktir_emulator::resident::ResidentExecutor::new(p.module.clone(), &p.spec).unwrap();
    fresh.set_sources(&refs_b).unwrap();
    let reference = read(&fresh.run(&[&key]).unwrap());

    // REUSED executor (the decode-loop shape): full sources with input A + run to warm
    // the weight cache, then a PARTIAL set_sources with ONLY the new input B + run. The
    // constant weights stay resident across the partial update; the result MUST equal
    // the fresh executor's. A stale cached weight (or KV buffer) makes it diverge.
    let mut reused =
        ktir_emulator::resident::ResidentExecutor::new(p.module.clone(), &p.spec).unwrap();
    reused.set_sources(&refs_a).unwrap();
    let _ = reused.run(&[&key]).unwrap(); // warm the weight cache
    reused.set_sources(&input_b).unwrap(); // partial update — only the input changes
    let step2 = read(&reused.run(&[&key]).unwrap());

    let max_abs = reference
        .iter()
        .zip(&step2)
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f32, f32::max);
    assert_eq!(reference.len(), step2.len(), "length mismatch");
    eprintln!("multistep partial set_sources: max-abs vs fresh = {max_abs:.6}");
    assert!(
        max_abs < 1e-3,
        "multi-step decode diverged from fresh by {max_abs} — the weight cache served \
         a stale/wrong buffer across set_sources (the bug the one-shot golden can't see)"
    );

    // PERF: the constant model weights must STAY RESIDENT across per-step set_sources
    // (the decode-loop shape) — NOT re-decode every token (the 2x regression). Measure
    // a FULL cold reload (misses on a pass that re-decodes everything) vs the per-step
    // misses (which should only be the few forward-written KV operands), and assert the
    // per-step count is a small FRACTION of the full reload — i.e. most weights kept.
    use std::sync::atomic::Ordering;
    let misses = || ktir_emulator::metal::WEIGHT_CACHE_MISSES.load(Ordering::Relaxed);
    // A full reload: clear everything, then one pass repopulates EVERY cached weight.
    ktir_emulator::metal::clear_weight_cache();
    let m0 = misses();
    let _ = reused.run(&[&key]).unwrap();
    let full_reload = misses() - m0;
    // Per-step updates: only the input changes; constant weights must stay resident.
    let mut steps = 0usize;
    let m1 = misses();
    for i in 0..4 {
        let inp: Vec<(&str, Arg)> = args
            .iter()
            .filter(|(n, _)| n == input_name)
            .map(|(n, a)| (n.as_str(), if i % 2 == 0 { perturb(a) } else { a.clone() }))
            .collect();
        reused.set_sources(&inp).unwrap();
        let _ = reused.run(&[&key]).unwrap();
        steps += 1;
    }
    let per_step = (misses() - m1) / steps.max(1);
    eprintln!(
        "decode residency: {per_step} weight-cache misses/step vs {full_reload} on a full reload \
         ({}% kept resident)",
        100 - (per_step * 100 / full_reload.max(1))
    );
    // Keeping the constant weights resident leaves only the few forward-written (KV)
    // operands to re-read — well under half a full reload. (Before the fix this was a
    // FULL reload every step — the 2x decode regression.)
    assert!(
        per_step * 2 < full_reload,
        "weights are NOT staying resident across set_sources ({per_step}/step vs {full_reload} \
         full reload) — the per-token re-decode regression is back"
    );
}

#[cfg(metal)]
#[test]
#[ignore = "real-model e2e RESIDENT ms/pass (hermetic — fixtures + HF weights); run --release --ignored --nocapture"]
fn time_smollm2_135m_decode_resident() {
    time_resident_e2e("smollm2-135m", "HuggingFaceTB/SmolLM2-135M");
}

#[cfg(metal)]
#[test]
#[ignore = "real-model e2e RESIDENT ms/pass (hermetic — fixtures + HF weights); run --release --ignored --nocapture"]
fn time_smollm2_135m_prefill_resident() {
    time_resident_e2e("smollm2-135m-prefill", "HuggingFaceTB/SmolLM2-135M");
}

#[cfg(metal)]
#[test]
#[ignore = "real-model e2e RESIDENT ms/pass (hermetic — fixtures + HF weights); run --release --ignored --nocapture"]
fn time_llama_3_2_1b_decode_resident() {
    time_resident_e2e("llama-3.2-1b", "unsloth/Llama-3.2-1B-Instruct");
}

#[cfg(metal)]
#[test]
#[ignore = "real-model e2e RESIDENT ms/pass (hermetic — fixtures + HF weights); run --release --ignored --nocapture"]
fn time_llama_3_2_1b_prefill_resident() {
    time_resident_e2e("llama-3.2-1b-prefill", "unsloth/Llama-3.2-1B-Instruct");
}

// ---------------------------------------------------------------------------
// LAST-TOKEN-ONLY MODE — correctness + perf.
//
// Autoregressive generation only needs the LAST token's logits to pick the next
// token; the other m-1 prefill rows of the lm_head projection are pure waste.
// `ResidentExecutor::set_last_token_only(true)` rewrites the final result GEMM to
// compute only output row m-1, turning the [m,vocab] lm_head into a [1,vocab] one.
// ---------------------------------------------------------------------------

/// CORRECTNESS: the last-token-only logits must equal the full all-rows path's
/// LAST row (within f16 tolerance and with the SAME argmax). Hermetic — fixtures +
/// public HF weights, the same harness the `*_real_forward` golden tests use.
#[cfg(metal)]
fn last_token_equiv(fixture: &str, repo: &str) {
    let dir = fixture_dir(fixture);
    if !dir.join("manifest.json").is_file() {
        eprintln!("{fixture}: no fixture manifest — skipping");
        return;
    }
    let p = load_program(&dir);
    let Some(w) = Weights::fetch(repo) else {
        eprintln!("{fixture}: could not fetch {repo} (offline?) — skipping");
        return;
    };
    let args = build_args(&dir, &p, &w);
    let refs: Vec<(&str, Arg)> = args.iter().map(|(n, a)| (n.as_str(), a.clone())).collect();
    let key = format!("t{}", p.result_id);
    let (m, vocab) = p.shape[&p.result_id];

    // FULL all-rows path.
    let mut exec = ktir_emulator::resident::ResidentExecutor::new(p.module.clone(), &p.spec)
        .expect("build resident executor");
    exec.set_sources(&refs).expect("marshal weights once");
    let full = exec
        .run(&[&key])
        .expect("full run")
        .get(&key)
        .expect("result")
        .data
        .clone();

    // LAST-TOKEN-only path (same executor + resident weights — no re-marshal).
    exec.set_last_token_only(true);
    let last = exec
        .run(&[&key])
        .expect("last-token run")
        .get(&key)
        .expect("result")
        .data
        .clone();

    // Compare the last-token output's LAST row to the full path's LAST row.
    let row = (m - 1) * vocab..m * vocab;
    let f = &full[row.clone()];
    let l = &last[row];
    let max_abs = f
        .iter()
        .zip(l)
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f32, f32::max);
    let arg_full = argmax(f);
    let arg_last = argmax(l);
    eprintln!(
        "{fixture} last-token-only: last-row max-abs vs full {max_abs:.4}, \
         argmax full={arg_full} last={arg_last} (m={m}, vocab={vocab})"
    );
    assert!(
        last.iter().all(|x| x.is_finite()),
        "{fixture}: non-finite last-token output"
    );
    assert_eq!(
        arg_full, arg_last,
        "{fixture}: last-token argmax differs from the full path's last row"
    );
    // f16 GEMM rounding only — the SAME activation row through the SAME weight, so
    // the band is tight (a few e-1 like the golden tests' max_abs).
    assert!(
        max_abs <= 0.5,
        "{fixture}: last-token last-row diverges from the full path by {max_abs}"
    );
}

#[cfg(metal)]
#[test]
fn last_token_equiv_llama_3_2_1b_prefill() {
    if skip_heavy_llama_in_ci() {
        return;
    }
    last_token_equiv("llama-3.2-1b-prefill", "unsloth/Llama-3.2-1B-Instruct");
}

#[cfg(metal)]
#[test]
fn last_token_equiv_smollm2_135m_prefill() {
    last_token_equiv("smollm2-135m-prefill", "HuggingFaceTB/SmolLM2-135M");
}

/// PERF: median ms/pass through the RESIDENT path, all-rows vs last-token-only,
/// with KTIR_SEG_PROF=1 to see the lm_head segment ms shrink. `#[ignore]` (heavy).
#[cfg(metal)]
fn time_last_token(fixture: &str, repo: &str) {
    let dir = fixture_dir(fixture);
    if !dir.join("manifest.json").is_file() {
        eprintln!("{fixture}: no fixture manifest — skipping");
        return;
    }
    let p = load_program(&dir);
    let Some(w) = Weights::fetch(repo) else {
        eprintln!("{fixture}: could not fetch {repo} (offline?) — skipping");
        return;
    };
    let args = build_args(&dir, &p, &w);
    let refs: Vec<(&str, Arg)> = args.iter().map(|(n, a)| (n.as_str(), a.clone())).collect();
    let key = format!("t{}", p.result_id);
    let iters: usize = std::env::var("ITERS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(5)
        .max(3);

    let mut exec = ktir_emulator::resident::ResidentExecutor::new(p.module.clone(), &p.spec)
        .expect("build resident executor");
    exec.set_sources(&refs).expect("marshal weights once");

    let bench = |exec: &mut ktir_emulator::resident::ResidentExecutor| -> f64 {
        exec.run(&[&key]).expect("warmup");
        let mut times: Vec<f64> = Vec::with_capacity(iters);
        for _ in 0..iters {
            let t = std::time::Instant::now();
            exec.run(&[&key]).expect("timed run");
            times.push(t.elapsed().as_secs_f64() * 1e3);
        }
        times.sort_by(|a, b| a.partial_cmp(b).unwrap());
        times[times.len() / 2]
    };

    exec.set_last_token_only(false);
    eprintln!("=== {fixture} ALL-ROWS ===");
    let all_ms = bench(&mut exec);
    exec.set_last_token_only(true);
    eprintln!("=== {fixture} LAST-TOKEN-ONLY ===");
    let last_ms = bench(&mut exec);
    let (m, _v) = p.shape[&p.result_id];
    eprintln!(
        "{fixture} (m={m}, {iters} passes): all-rows {all_ms:.1} ms/pass | \
         last-token {last_ms:.1} ms/pass | {:.2}x",
        all_ms / last_ms
    );
}

#[cfg(metal)]
#[test]
#[ignore = "last-token-only perf (hermetic); run --release --ignored --nocapture --test-threads=1 (set KTIR_SEG_PROF=1)"]
fn time_last_token_llama_3_2_1b_prefill() {
    time_last_token("llama-3.2-1b-prefill", "unsloth/Llama-3.2-1B-Instruct");
}

#[cfg(metal)]
#[test]
#[ignore = "last-token-only perf (hermetic); run --release --ignored --nocapture --test-threads=1 (set KTIR_SEG_PROF=1)"]
fn time_last_token_smollm2_135m_prefill() {
    time_last_token("smollm2-135m-prefill", "HuggingFaceTB/SmolLM2-135M");
}
